logging:
  level:
    org.springframework.security: DEBUG

zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      path: /resources/**
      url: http://localhost:9000
      sensitive-headers:

security:
  sessions: ALWAYS
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      #registered-redirect-uri: http://localhost:8080
      #use-current-uri: false
      #pre-established-redirect-uri: http://localhost:8080
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  basic:
    enabled: false