server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      grantType: authorization_code
      scope: openid
      #registered-redirect-uri: http://localhost:8080/ui
    resource:
      userInfoUri: http://localhost:9999/uaa/user